Fix optimizer resume bug (#411)
<!-- markdownlint-disable -->

PLEASE FILL IN THE PR DESCRIPTION HERE ENSURING ALL CHECKLIST ITEMS (AT
THE BOTTOM) HAVE BEEN CONSIDERED.

## Purpose
Fix optimizer resume dtype error.    
<!--- Why your changes are needed -->

## Description

When we resume distributed training from the previous `best_checkpoint`,
there is a type mismatch bug.
```
RuntimeError: aten._foreach_mul_.Scalar: got mixed torch.Tensor and DTensor, need to convert all torch.Tensor to DTensor before calling distributed operators!
```
This is because `init_best_val_loss_from_checkpoint_best()` was called
inside `setup_model()`, we ran a forward pass in validation to calculate
the `best_val_loss`. This forward pass converts model parameters into
DTensors with some other bookkeeping params and
`set_optimizer_state_dict` then crashes because it was expecting clean
tensors.

There's another issue with `step` data type now because
`convert_float_dtype` casts all floating-point tensors to bfloat16 when
saving/loading, including Adam's step counters. PyTorch's
`_group_tensors_by_device_and_dtype` only exempts CPU step tensors that
are float32 or float64, so bfloat16 step tensors cause a device/dtype
grouping error at optimizer.step().

Now we're saving `best_val_loss` in a json along with best checkpoint
and loading it directly instead of running a full validation forward
pass to avoid this type mismatch and casting step dtype back to float32.

<!--- High-level concise summary of changes -->

## Related Issue

<!--- Link related issue if applicable -->

## Tests

Added
`/home/shanjiaz/speculators/tests/e2e/smoke/test_resume_optimizer.py`
and ran locally to make sure it captures this bug properly. Had to
update `tests/unit/train/test_checkpoint.py` as well because the flow is
now different.

<!--- Please describe in detail how you tested your changes. -->

I have filled in:

- [x] The purpose of the PR, such as "Fix some issue (link existing
issues this PR will resolve)".
- [x] The test plan/results, such as providing test command and pasting
the results.
- [ ] (Optional) The necessary documentation update.
- [x] I (a human) have written or reviewed the code in this pr to the
best of my ability.

---------

Signed-off-by: shanjiaz <zsjwpianpian@gmail.com>